### ISSUE TITLE
Snake doesn't move on RHEL8, only shows one line on MacOS Monterey

### ISSUE THREAD

**Issue by IOMadness** [wick3dr0se/snake#1]
On my Mac running MacOS Monterey 12.5.1 using terminal, installing with:
git clone https://github.com/wick3dr0se/snake && cd ${_##*/}

...then running with
bash snake.sh

...it only shows one line at the top of the terminal window, which doesn't move, but does extend to the right if you move right.

On RHEL8.6 (4.18.0-372.16.1.el8_6.x86_64), performing the same steps in a terminal window results in the full game "world" showing, but the snake doesn't move, and only extends itself as you press the movement keys h,j,k,l. The game does not end if you run into yourself, or the wall, and there are no items to pick up to extend the length of the snake, or obstacles to risk running into.

bash version on MacOS I used:
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)

bash version on RHEL8.6:
GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu)

**Comment by wick3dr0se** [comment]
Currently it is just a snake that moves and becomes larger. I'm working to create a dynamic snake that will remain shape throughout bends and increase through 'eating' blocks. I just hacked this up the other night, so it shouldn't take me long to come up with some method to 'move' the snake. Right now it's super alpha state.

I should have specified, but this will only run on systems with BASH v5+. I can knock that down to ~4.2 by setting a fallback for checkwinsize. I'll add that to the description. I'm not familiar with MacOS but you can update BASH, maybe through homebrew

**Comment by wick3dr0se** [comment]
@IOMadness The game is fully functional now. If you get a change, let me know what you think!
