### ISSUE TITLE
You can walk into yourself

### ISSUE THREAD

**Issue by talwat** [wick3dr0se/snake#4]
If you go in a circle, you simply will not die. In fact, there is no way to die in this game exactly.

Additionally, if you are facing up then you are able to change direction directly to down, which isn't possible in normal snake.

**Comment by wick3dr0se** [comment]
That's expected for now; These are work in progress implementations I mentioned in the original post. I'll keep this issue up till it's done!

**Comment by talwat** [comment]
Awesome, this is a really cool project overall. I am fancying this trend of straying away from dependency heavy programs.

**Comment by wick3dr0se** [comment]
@talwat It can't walk into itself now 🙃

**Comment by talwat** [comment]
It's super cool that this project is still going. I use it to test whether my bash install is fully functional. Keep on going :)

**Comment by wick3dr0se** [comment]
@talwat Thanks, I took a long break (as usual when I get frustrated and can't figure it out). Check out the TUI file manager I wrote too then. Uses the same base keybindings and of course it's bash 😅
