### ISSUE TITLE
subscript error

### ISSUE THREAD

**Issue by DLewis01** [wick3dr0se/snake#7]
./snake.sh: line 73: snake: bad array subscript                         ./snake.sh: line 82: snake: bad array subscript
./snake.sh: line 82: snake: bad array subscript: read: .7: invalid timeout specification
./snake.sh: line 73: snake: bad array subscript
SNAKE x:62 y:28 len:3 spe:20./snake.sh: line 25: read: .7: invalid timeout specification

**Comment by wick3dr0se** [comment]
@DLewis01 What version of bash are you using?

**Comment by wick3dr0se** [comment]
@DLewis01 Closing
