### ISSUE TITLE
Reversing ends game

### ISSUE THREAD

**Issue by creeper6530** [wick3dr0se/snake#8]
Whenever I press the exact opposite direction than my snake is currently moving, I get immediate game over. This is somewhat annoying when I mispress a button, and makes sharp 180s and zig-zags much harder to pull off.

**Comment by wick3dr0se** [comment]
@creeper6530 I implemented a stop on opposite directions. Now the game will pause on those accidental presses :smile:

Let me know if this works for you

**Comment by creeper6530** [comment]
Works perfectly. Thanks!
